# Generated by Django 6.0 on 2026-01-06 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('current_phase', models.IntegerField(choices=[(0, 'Environment Setup'), (1, 'User System'), (2, 'Project Management'), (3, 'System Logic'), (4, 'User Questions'), (5, 'Requirement Lock'), (6, 'Blueprint Generation'), (7, 'Execution Guide'), (8, 'Testing'), (9, 'Deployment'), (10, 'Final Export')], default=0)),
                ('requirements_data', models.JSONField(blank=True, default=dict)),
                ('blueprint_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
