# Generated by Django 6.0 on 2026-01-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation_md',
            field=models.TextField(blank=True, null=True),
        ),
    ]
