# Generated by Django 6.0 on 2026-01-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_documentation_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documentation_md',
        ),
        migrations.AddField(
            model_name='project',
            name='docs_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
